
# ==============================
# General Application Settings
# ==============================
spring.application.name=bankingsystem
server.port=8080


# ==============================
# Logging & Metrics
# ==============================
logging.level.root=INFO
logging.level.com.example.bankingsystem.account.metrics=INFO
management.endpoints.web.exposure.include=*
management.metrics.enable.all=true

# ==============================
# PostgreSQL Datasource
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=auth_user
spring.datasource.password=auth_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# Hibernate / JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Hibernate Batch Settings
#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# Hibernate Debug / Stats
spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.session.events.log=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.stat=DEBUG

# ==============================
# Internationalization / Messages
# ==============================
spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8

# ==============================
# Spring Batch
# ==============================
#spring.batch.initialize-schema=always

# ==============================
# Internal Token (From Gateway)
# ==============================
internal.jwt.secret=dbad3483d4743164f04f95703fbaad6a352898dc9cb9d4d4340954ef8c94b5d0
internal.jwt.expiration-ms=3600000